version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/vhost.d:/etc/nginx/vhost.d
      - ./conf/html:/usr/share/nginx/html
      - ./conf/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - ./logs:/var/log/nginx
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    restart: always

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/certs:/etc/nginx/certs:rw
      - /etc/localtime:/etc/localtime:ro
    restart: always

  cloudflare-companion:
    image: tiredofit/nginx-proxy-cloudflare-companion
    container_name: cloudflare-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CF_EMAIL=noemail@example.org
      - CF_TOKEN=1234
      - CF_ZONE_ID=foo
      - CF_TARGET_DOMAIN=host.example.org
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy
